//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Visit
    {
        public int pkID { get; set; }
        public int fkDocID { get; set; }
        public System.DateTime SDate { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
        public Nullable<int> fkPID { get; set; }
        public Nullable<int> fkVTID { get; set; }
        public Nullable<int> fkVisitStatus { get; set; }
        public string hashid { get; set; }
    
        public virtual tbl_Doctors tbl_Doctors { get; set; }
        public virtual tbl_Patient tbl_Patient { get; set; }
        public virtual tbl_VisitStatus tbl_VisitStatus { get; set; }
        public virtual tbl_VisitType tbl_VisitType { get; set; }
    }
}
