//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_VisitPerDoctors
    {
        public int pkID { get; set; }
        public int fkDocID { get; set; }
        public int fkVisitID { get; set; }
        public long Duration { get; set; }
    
        public virtual tbl_Doctors tbl_Doctors { get; set; }
        public virtual tbl_VisitType tbl_VisitType { get; set; }
    }
}
