//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Visit
    {
        public int pkID { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public int fkDocID { get; set; }
        public System.DateTime SDate { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
        public Nullable<int> fkPID { get; set; }
        public Nullable<int> fkVTID { get; set; }
        public string PDate { get; set; }
        public string PTime { get; set; }
        public string pName { get; set; }
        public string pFamily { get; set; }
        public string pMobile { get; set; }
        public string Type { get; set; }
        public Nullable<int> fkVisitStatus { get; set; }
        public string VisitStatus { get; set; }
        public string hashid { get; set; }
        public string PNC { get; set; }
    }
}
